name: "AVE Websocket"
version: "1.5"
slug: "avews"
description: "Custom integration for AVE webserver"
arch:
  - amd64
  - armv7
startup: "application"
boot: "auto"
url: "https://github.com/emmeoerre/avews/tree/main/avews"
options:
  web_server_address: "192.168.1.10"
  sync_antitheft: true
  poll_interval: 10
  verbose: false
schema:
  web_server_address: str
  sync_antitheft: bool
  poll_interval: int
  verbose: bool
host_network: true
privileged:
  - NET_ADMIN
homeassistant_api: true
image: https://github.com/emmeoerre/avews/blob/cc5ec7b586c0de74a78eb575292beb0c4817a0a3/avews/misc/logo.png