name: "AVE Websocket"
version: "1.8.4"
slug: "avews"
description: "Custom integration for AVE webserver"
arch:
  - amd64
  - armv7
startup: "application"
boot: "auto"
url: "https://github.com/emmeoerre/avews/tree/main/avews"
options:
  web_server_address: "192.168.1.10"
  web_server_mac: "00:00:00:00:00:00"
  sync_antitheft: true
  poll_interval: 10
  sync_lights_startup: true
  subscribe_to_events: false
  verbose: false
schema:
  web_server_address: str
  web_server_mac: str
  sync_antitheft: bool
  poll_interval: int
  sync_lights_startup: bool
  subscribe_to_events: bool
  verbose: bool
# host_network: true
# privileged:
#   - NET_ADMIN
homeassistant_api: true
